services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        volumes:
            - ./frontend/src:/src

    backend:
        build: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/app:/app