FROM golang:1.22.5-alpine

WORKDIR /app

COPY ./app /app

RUN go mod download

# 開発環境
RUN go install github.com/air-verse/air@latest

EXPOSE 8080

# 開発環境
CMD ["air"]

# 本番環境
# CMD ["go", "run", "main.go"]
