name: Feature Report
about: Suggest an idea for this project
title: ''
labels: feature
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Issueを記入してくれてありがとうございます!
  - type: textarea
    id: directory
    attributes:
      label: 作業場所
      description: 作業するディレクトリを書いてください。
      placeholder: frontend / backend / db / pgadmin
    validations:
      required: true
  - type: textarea
    id: about-feature
    attributes:
      label: 新規機能の概要
      description: 新規機能の概要を書いてください.
      placeholder: 〇〇の開発をする.
    validations:
      required: true
